config/routes.rb
PuavoUsers::Application.routes.draw do

  root :to => "schools#index"

  match '/menu' => 'menu#index', :via => :get

  scope :path => "restproxy" do
    match '(*url)' => 'rest#proxy', :via => [:get, :post, :put], :format => false
  end

  scope :path => "users" do
    resources :ldap_services
    resource :organisation_external_services

    scope :path => ':school_id' do
      match 'roles/:id/select_school' => 'roles#select_school', :as => :select_school_role, :via => :get
      match 'roles/:id/select_role' => 'roles#select_role', :as => :select_role_role, :via => :post
      match 'roles/:id/add_group/:group_id' => 'roles#add_group', :as => :add_group_role, :via => :put
      match 'roles/:id/remove_group/:group_id' => 'roles#remove_group', :as => :remove_group_role, :via => :put
      match 'roles/:id/remove_users' => 'roles#remove_users', :as => :remove_users_role, :via => :put
    end

    scope :path => ':school_id' do
      resource :rename_groups
      resources :roles
    end
    resources :roles

    namespace :schools do
      scope :path => ':school_id' do
        resource :external_services
      end
    end

    scope :path => ':school_id' do
      resources :printer_permissions
    end

    scope :path => ':school_id' do
      match 'lists' => 'lists#index', :as => :lists, :via => :get
      match 'lists/:id' => 'lists#download', :as => :download_list, :via => :post
    end

    match 'schools/:id/admins' => 'schools#admins', :as => :admins_school, :via => :get
    match 'schools/:id/add_school_admin/:user_id' => 'schools#add_school_admin', :as => :add_school_admin_school, :via => :put
    match 'schools/:id/remove_school_admin/:user_id' => 'schools#remove_school_admin', :as => :remove_school_admin_school, :via => :put
    match 'schools/:id/wlan' => 'schools#wlan', :as => :wlan_school, :via => :get
    match 'schools/:id/wlan_update' => 'schools#wlan_update', :as => :wlan_update_school, :via => :put
    match 'schools/:id/external_services' => 'external_services#index', :as => :external_services_school, :via => :get
    resources :schools

    scope :path => ':school_id' do
      match "groups/:id/remove_user/:user_id" => "groups#remove_user", :as => "remove_user_group", :via => :put
      match "groups/:id/add_user/:user_id" => "groups#add_user", :as => "add_user_group", :via => :put
      match "groups/:id/user_search" => "groups#user_search", :as => :user_search, :via => :get
      match 'groups/:id/members' => 'groups#members', :as => :add_role_group, :via => :get
      match 'groups/:id/add_role/:role_id' => 'groups#add_role', :as => :add_role_group, :via => :put
      match 'groups/:id/delete_role/:role_id' => 'groups#delete_role', :as => :delete_role_group, :via => :put
      match 'users/:id/select_school' => 'users#select_school', :as => :select_school_user, :via => :get
      match 'users/:id/select_role' => 'users#select_role', :as => :select_role_user, :via => :post
      match 'users/change_school' => 'users#change_school', :as => :change_school_users, :via => :post
      match 'users/:id/group' => 'users#group', :as => :group_user, :via => :get
      match 'users/:id/add_group' => 'users#add_group', :as => :add_group_user, :via => :put
      match 'import_tool' => 'import_tool#index', :via => :get
      match 'username_redirect/:username' => 'users#username_redirect', :via => :get, :constraints => { :username => /[^\/]+/ }
    end


    scope :path => ':school_id' do
      resources :users
      match 'users/:id/image' => 'users#image', :as => :image_user, :via => :get
    end

    resources :users

    scope :path => ':school_id' do
      resources :groups
    end
    resources :groups

    match '/login' => 'sessions#new', :as => :login, :via => :get
    match '/login' => 'sessions#create', :as => :login, :via => :post
    match '/logout' => 'sessions#destroy', :as => :logout, :via => :delete
    match '/logo' => 'sessions#logo', :as => :logo, :via => :get, :format => :png
    match '/login/helpers' => 'sessions#login_helpers', :as => :login_helpers, :via => :get, :format => :js
    match '/login/theme' => 'sessions#theme', :as => :login_theme, :via => :get, :format => :css

    resources :sessions
    match 'schools/:id/image' => 'schools#image', :as => :image_school, :via => :get
    match '/' => 'schools#index'
    match ':school_id/users/import/refine' => 'users/import#refine', :as => :refine_users_import, :via => :post
    match ':school_id/users/import/validate' => 'users/import#validate', :as => :validate_users_import, :via => [:post]
    match ':school_id/users/import/new' => 'users/import#new', :as => :new_users_import, :via => :get
    match ':school_id/users/import/status/:job_id' => 'users/import#status', :as => :import_status, :via => :get
    match ':school_id/users/import/render_pdf/:job_id' => 'users/import#render_pdf', :as => :render_pdf, :via => :post
    match ':school_id/users/import/' => 'users/import#create', :as => :create_users_import, :via => :post
    match ':school_id/users/import/user_validate' => 'users/import#user_validate', :as => :user_validate_users_import, :via => :post
    match ':school_id/users/import/options' => 'users/import#options', :as => :options_users_import, :via => :get
    match ':school_id/users/import/download' => 'users/import#generate_passwords_pdf', :as => :generate_passwords_pdf, :via => :post

    scope :path => "password" do
      get( '', :to => 'password#edit',
           :as => :password )
      get( 'edit',
           :to => 'password#edit',
           :as => :edit_password )
      get( 'own',
           :to => 'password#own',
           :as => :own_password )
      put( '',
           :to => 'password#update' )
      get( 'forgot',
           :to => 'password#forgot',
           :as => :forgot_password )
      put( 'forgot',
           :to => 'password#forgot_send_token',
           :as => :forgot_send_token_password )
      get( ':jwt/reset',
           :to => 'password#reset',
           :as => :reset_password,
           constraints: { jwt: /.+/ } )
      post( ':jwt/reset',
            :to => 'password#reset_update',
            :as => :reset_update_password,
            constraints: { jwt: /.+/ } )
      get( 'successfully/:message',
           :to => 'password#successfully',
           :as => :successfully_password )
    end

    match( 'email_confirm' => 'email_confirm#confirm',
           :as => :confirm_email,
           :via => :put )
    match( 'email_confirm/successfully' => 'email_confirm#successfully',
           :as => :successfully_email_confirm,
           :via => :get )
    match( 'email_confirm/:jwt' => 'email_confirm#preview',
           :as => :preview_email_confirm,
           :via => :get,
           :constraints => { jwt: /.+/ } )

    match 'themes/:theme' => 'themes#set_theme', :as => :set_theme
    resources :admins

    match 'owners' => 'organisations#owners', :as => :owners_organisation, :via => :get
    match 'remove_owner/:user_id' => 'organisations#remove_owner', :as => :remove_owner_organisations, :via => :put
    match 'add_owner/:user_id' => 'organisations#add_owner', :as => :add_owner_organisations, :via => :put

    match 'wlan' => 'organisations#wlan', :as => :wlan_organisation, :via => :get
    match 'wlan_update' => 'organisations#wlan_update', :as => :wlan_update_organisation, :via => :put

    resource :organisation, :only => [:show, :edit, :update]
    match "search" => "users_search#index", :as => :search_index
    resource :profile, :only => [:edit, :update, :show]
    match 'profile/image' => 'profiles#image', :as => :image_profile, :via => :get
  end

  scope :path => "devices" do
    match '/' => 'schools#index'
    match 'sessions/show' => 'api/v1/sessions#show', :via => :get
    resources :sessions

    match 'hosts/types' => 'hosts#types'

    scope :path => ':school_id' do
      match 'devices/:id/select_school' => 'devices#select_school', :as => 'select_school_device', :via => :get
      match 'devices/:id/change_school' => 'devices#change_school', :as => 'change_school_device', :via => :post
      match 'devices/:id/image' => 'devices#image', :as => 'image_device', :via => :get

      resources :devices

      match( 'devices/:id/revoke_certificate' => 'devices#revoke_certificate',
             :as => 'revoke_certificate_device',
             :via => :delete )

    end
    
    match 'servers/:id/image' => 'servers#image', :as => 'image_server', :via => :get
    match( 'servers/:id/revoke_certificate' => 'servers#revoke_certificate',
           :as => 'revoke_certificate_server',
           :via => :delete )
    resources :servers

    namespace :api do
      namespace :v2 do
        match( 'devices/by_hostname/:hostname' => 'devices#by_hostname',
               :as => 'by_hostname_api_v2_device',
               :via => :get )
        resources :devices
        resources :servers
      end
    end

    resources :printers, :except => [:show, :new]

    match "search" => "devices_search#index"

    match '/auth' => 'sessions#auth', :via => :get
    
  end

    namespace :api do
      namespace :v2 do
        match( 'hosts/sign_certificate' => 'hosts#sign_certificate',
               :as => 'hosts_sign_certificate',
               :via => :post,
               :format => :json )
      end
    end

  ["api/v2/", ""].each do |prefix|
    match("#{ prefix }external_files" => "external_files#index", :via => :get)
    match("#{ prefix }external_files" => "external_files#upload", :via => :post)
    match(
      "#{ prefix }external_files/:name" => "external_files#get_file",
      :name => /.+/,
      :format => false,
      :via => :get,
      :as => "download_external_file"
    )
    match(
      "#{ prefix }external_files/:name" => "external_files#destroy",
      :name => /.+/,
      :format => false,
      :via => :delete,
      :as => "destroy_external_file"
    )
  end

end

app/models/group.rb
class Group < BaseGroup
  include HasPrinterMixin
  ldap_mapping( :dn_attribute => "puavoId",
                :prefix => "ou=Groups",
                :classes => ['top', 'posixGroup', 'puavoEduGroup','sambaGroupMapping'] )
  has_many :members, :class_name => "User", :wrap => "member", :primary_key => "dn"
  has_many :memberUids, :class_name => "User", :wrap => "memberUid", :primary_key => "uid"
  has_many :primary_members, :class_name => 'User', :foreign_key => 'gidNumber', :primary_key => 'gidNumber'

  belongs_to( :school, :class_name => 'School',
              :foreign_key => 'puavoSchool',
              :primary_key => 'dn' )

  belongs_to( :roles,
              :class_name => "Role",
              :many => "puavoMemberGroup",
              :primary_key => "dn" )

  validate :validate

  def validate
    unless self.cn.to_s =~ /^[a-z0-9-]+$/
      errors.add( :cn, I18n.t("activeldap.errors.messages.group.invalid_characters") )
    end
    if self.displayName.to_s.empty?
      errors.add( :displayName, I18n.t("activeldap.errors.messages.blank",
                                       :attribute => I18n.t("activeldap.attributes.group.displayName")) )
    end
  end

  def to_s
    self.displayName
  end
  
  def remove_user(user)
    self.ldap_modify_operation(:delete, [{ "memberUid" => [user.uid]},
                                         { "member" => [user.dn.to_s] }])
  end

  def as_json(*args)
    { "school_id" => self.school.puavoId,
      "abbreviation" => self.cn.to_s,
      "gid" => self.gidNumber,
      "name" => self.displayName,
      "puavo_id" => self.puavoId,
      "samba_SID" => self.sambaSID,
      "samba_group_type" => self.sambaGroupType }
  end

  def member?(user_id)
    self.members.map{ |u| u.puavoId }.include?(user_id.to_i)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  # GET /:school_id/groups/:id/members
  def members
    @group = Group.find(params[:id])

    @members = @group.members

    respond_to do |format|
      format.json  { render :json => @members }
    end
  end

  # GET /:school_id/groups
  # GET /:school_id/groups.xml
  def index
    if @school
      @groups = @school.groups.sort
    else
      @groups = Group.all.sort
    end
    if params[:memberUid]
      @groups.delete_if{ |g| !Array(g.memberUid).include?(params[:memberUid]) }
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @groups }
      format.json { render :json => @groups }
    end
  end

  # GET /:school_id/groups/1
  # GET /:school_id/groups/1.xml
  def show
    @group = Group.find(params[:id])

    @members = @group.members

    @roles = @group.roles.sort
    @other_roles = Role.all.delete_if do |p| @roles.include?(p) end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /:school_id/groups/new
  # GET /:school_id/groups/new.xml
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /:school_id/groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /:school_id/groups
  # POST /:school_id/groups.xml
  def create
    @group = Group.new(params[:group])

    @group.puavoSchool = @school.dn

    respond_to do |format|
      if @group.save
        flash[:notice] = t('flash.added', :item => t('activeldap.models.group'))
        format.html { redirect_to( group_path(@school, @group) ) }
        format.xml  { render :xml => @group, :status => :created, :location => @group }
      else
        flash[:alert] = t('flash.create_failed', :model => t('activeldap.models.group').downcase )
        format.html { render :action => "new" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /:school_id/groups/1
  # PUT /:school_id/groups/1.xml
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        flash[:notice] = t('flash.updated', :item => t('activeldap.models.group'))
        format.html { redirect_to( group_path(@school, @group) ) }
        format.xml  { head :ok }
      else
        flash[:alert] = t('flash.save_failed', :model => t('activeldap.models.group') )
        format.html { render :action => "edit" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /:school_id/groups/1
  # DELETE /:school_id/groups/1.xml
  def destroy
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.destroy
        flash[:notice] = t('flash.destroyed', :item => t('activeldap.models.group'))
        format.html { redirect_to(groups_url) }
        format.xml  { head :ok }
      else
        format.html { redirect_to(groups_url) }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  def remove_user
    @group = Group.find(params[:id])
    @user = User.find(params[:user_id])

    @group.remove_user(@user)
    @group.reload


    @members = @group.members

    respond_to do |format|
      format.html { render :text => "OK" }
      format.js
    end
  end

  def add_user
    @group = Group.find(params[:id])
    @user = User.find(params[:user_id])

    Group.ldap_modify_operation(@group.dn, :add, [{ "memberUid" => [@user.uid]},
                                                  { "member" => [@user.dn.to_s] }])

    @group.reload


    @members = @group.members

    respond_to do |format|
      format.html { render :text => "OK" }
      format.js
    end
  end

  def add_role
    @group = Group.find(params[:id])
    @role = Role.find(params[:role_id])

    respond_to do |format|
      if @role.groups << @group && @group.save
        @role.update_associations
        flash[:notice] =  t('flash.group.role_added')
        format.html { redirect_to( group_path(@school, @group) ) }
      else
        flash[:notice] = t('flash.group.role_added')
        format.html { redirect_to( group_path(@school, @group) ) }
      end
    end
  end

  def delete_role
    @group = Group.find(params[:id])
    @role = Role.find(params[:role_id])

    respond_to do |format|
      if @role.groups.delete(@group) && @group.save
        @role.update_associations
        flash[:notice] =  t('flash.group.role_removed')
        format.html { redirect_to( group_path(@school, @group) ) }
      else
        flash[:alert] =  t('flash.group.role_removed_failed')
        format.html { redirect_to( group_path(@school, @group) ) }
      end
    end
  end

  def user_search
    @group = Group.find(params[:id])

    @users = User.words_search_and_sort_by_name(
      ["sn", "givenName", "uid"],
      lambda{ |v| "#{v['sn'].first} #{v['givenName'].first}" },
      lambda { |w| "(|(givenName=*#{w}*)(sn=*#{w}*)(uid=*#{w}*))" },
      params[:words] )

    @schools = Hash.new
    School.search_as_utf8( :scope => :one,
                   :attributes => ["puavoId", "displayName"] ).map do |dn, v|
      @schools[v["puavoId"].first] = v["displayName"].first
    end

    respond_to do |format|
      if @users.length == 0
        format.html { render :inline => '' }
      else
        format.html { render :user_search, :layout => false }
      end
    end

  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group, :url => path, :html => { :method => method } ) do |f| %>
<div class="no-table-form">
<p>
  <%= f.label :displayName %><br />
  <%= f.text_field :displayName %>
</p>
<p>
  <%= f.label :cn %><br />
  <%= f.text_field :cn %>
</p>
<p>
  <%= f.label :puavoEduGroupType %><br />
  <%= f.select :puavoEduGroupType, group_types_for_select %>
</p>
  <span>
  <%= f.submit submit_text, :class=>'btn' %>
  <div class="cancel"><%=link_to t('link.cancel'),  path, :class => 'btn btn-danger' %>
</span>
</div>
<% end %>

app/views/groups/_members.html.erb
  <h3><%= t('.title') %></h3>
  <% @members.each do |member| %>
  <div class="row">
    <div class="column_1">
      <%= "#{ member.givenName } #{ member.sn} (#{ member.uid })" %>
    </div>
    <div class="column_2">
      <%= link_to(t('.remove'), remove_user_group_path(:school_id => member.school.id, :id => @group.puavoId, :user_id => member.puavoId), :remote => true, :method => :put, :class => "btn") %>
    </div>
  </div>
  <% end %>

app/views/groups/add_user.js.erb
$(".members").html("<%= escape_javascript(render(:partial => "members")) %>")
$("#member_status_<%= @group.puavoId.to_s %>_<%= @user.puavoId.to_s %>").html("Jäsen")

app/views/groups/edit.html.erb
<h1><span><%= t('.title') %></span></h1>

<%= render :partial => 'form',
 :locals => { :path => group_path(@school, @group),
  :method => :put,
  :submit_text => t('link.update')
} %>
<% content_for :footer do %>
<ul>
  <li class="link_header">
    <%= link_to school_path(@school) do %>
    <span><%= t('layouts.application.schools') %></span>
    <% end %>
  </li>
  <% school_list.each do |school| %>
  <li<% if school_list.last == school %> class="last"<% end %>>
    <%= link_to school.displayName,  school_path(school) %>
  </li>
  <% end %>
</ul>
<ul>
<li class="link_header"><%= @school.displayName %></li>
<li><%= link_to users_path(@school) do %>
  <span><%= t('layouts.application.users') %></span>
<% end %>
</li>
  <li><%= link_to t('link.groups'), groups_path(@school) %></li>
  <li><%= link_to t('link.roles'), roles_path(@school) %></li>
  <li><a href="/devices/<%= @school.id%>/devices"><span><%= t('layouts.application.devices') %></span></a></li>
</ul>
<% end %>

app/views/groups/index.html.erb
<table class="list">
  <tr class="thead">
    <th><%= t('activeldap.attributes.group.displayName') %></th>
    <th><%= t('activeldap.attributes.group.cn') %></th>
    <th><%= t('activeldap.attributes.group.puavoEduGroupType') %></th>
    <th colspan="2"><%= t('.actions') %></th>
  </tr>

<% @groups.each do |group| %>
  <tr>
    <td data-title="<%=t('activeldap.attributes.group.displayName')%>">
      <%= link_to group.displayName, group_path(@school, group) %>
      <%= " (#{Array(group.memberUid).count})" %>
    </td>
    <td data-title="<%=t('activeldap.attributes.group.cn')%>">
      <%= group.cn %>
    </td>
    <td data-title="<%=t('activeldap.attributes.group.puavoEduGroupType')%>">
      <%= humanize_group_type(group.puavoEduGroupType) %>
    </td>
    <td data-title="<%=t('.actions')%>" class="table-actions">
      <%= link_to edit_group_path(@school, group), :class=> "btn" do%>
        <i class='icon-pencil'></i><%= t('link.edit') %>
      <% end %>
    </td>
    <td class="table-actions">
      <%= link_to group_path(@school, group), :confirm => t('general_confirm'), :method => :delete, :class=> "btn btn-danger" do%>
        <i class='icon-trash'></i><%= t('link.destroy')%>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

<% content_for :right do %>
<div>
  <%= link_to new_group_path(@school), :class => 'btn' do%>
  <i class='icon-plus'></i><%= t('link.new_group') %>
  <% end %>
</div>
<% end %>

app/views/groups/new.html.erb
<h1><span><%= t('.title') %></span></h1>

<%= render :partial => 'form', 
:locals => {
  :path => groups_path(@school),
  :method => :post,
  :submit_text => t('link.create')
} %>
<% content_for :footer do %>
<ul>
  <li class="link_header">
    <%= link_to school_path(@school) do %>
    <span><%= t('layouts.application.schools') %></span>
    <% end %>
  </li>
  <% school_list.each do |school| %>
  <li<% if school_list.last == school %> class="last"<% end %>>
    <%= link_to school.displayName,  school_path(school) %>
  </li>
  <% end %>
</ul>
<ul>
<li class="link_header"><%= @school.displayName %></li>
<li><%= link_to users_path(@school) do %>
  <span><%= t('layouts.application.users') %></span>
<% end %>
</li>
  <li><%= link_to t('link.groups'), groups_path(@school) %></li>
  <li><%= link_to t('link.roles'), roles_path(@school) %></li>
  <li><a href="/devices/<%= @school.id%>/devices"><span><%= t('layouts.application.devices') %></span></a></li>
</ul>
<% end %>

app/views/groups/remove_user.js.erb
$(".members").html("<%= escape_javascript(render(:partial => "members")) %>")

app/views/groups/show.html.erb
<% if new_group_management?(@school) %>
<table class="basic-info">
  <tr>
    <td>
      <b><%= t('activeldap.attributes.group.displayName') %>:</b>
    </td>
    <td>
      <%=h @group.displayName %>
    </td>
  </tr>
  <tr>
    <td>
      <b><%= t('activeldap.attributes.group.cn') %></b>:
    </td>
    <td>
      <%=h @group.cn %>
    </td>
  </tr>
  <tr>
    <td>
      <b><%= t('activeldap.attributes.group.gidNumber') %></b>:
    </td>
    <td>
      <%=h @group.gidNumber %>
    </td>
  </tr>
  <tr>
    <td>
      <b><%= t('activeldap.attributes.group.puavoEduGroupType') %></b>:
    </td>
    <td>
      <%=h humanize_group_type(@group.puavoEduGroupType) %>
    </td>
  </tr>
</table>

<div class="content-box list members">
  <%= render :partial => "members" %>
</div>

<div class="content-box list">
  <h3><%= t('.add_user_title') %></h3>
  <div class="row">
    <div class="column_1">
      <%= t('.description') %>
    </div>
  </div>

  <div class="row">
    <div class="column_1">
      <%= text_field_tag( "user_search",
          nil,
          :class => "user_search",
          :size => 50,
          :placeholder => t('.placeholder_for_search') ) %>
    </div>
  </div>
</div>

<% else %>

<p>
  <b><%= t('activeldap.attributes.group.displayName') %>:</b>
  <%=h @group.displayName %>
</p>

<p>
  <b><%= t('activeldap.attributes.group.cn') %>:</b>
  <%=h @group.cn %>
</p>

<p>
  <b><%= t('activeldap.attributes.group.gidNumber') %>:</b>
  <%=h @group.gidNumber %>
</p>

<p>
  <b><%= t('.roles_and_members') %>:</b><br />
  <span id="roles_and_members">
    <% @roles.each do |p| %>
      <%= "#{p.displayName} (#{p.school.displayName})" %>
      <%= link_to t('link.remove'), delete_role_group_path(@school, @group, p), :method => :put, :id => "remove_role_#{p.id}" %>
      <ul>
        <% p.members.each do |m| %>
          <li><%= link_to m.displayName, user_path(@school, m) %></li>
        <% end %>
      </ul>
    <% end %>
  </span>
</p>

<p>
  <b><%= t('.other_roles') %>:</b><br />
  <span id="other_roles">
  <% @other_roles.each do |p| %>
    <%= "#{p.displayName} (#{p.school.displayName})" %>
    <%= link_to t('link.add'), add_role_group_path(@school, @group, p), :method => :put, :id => "add_role_#{p.id}" %>
    <br />
  <% end %>
  </span>
</p>

<% end %>

<% content_for :right do %>
<ul class="sub-tools">
  <li>
    <%= link_to edit_group_path(@school, @group), :class => 'btn' do %>
      <i class="icon-pencil"></i><%= t('link.edit') %>
    <% end %>
  </li>
  <li class="tool">
    <span class="btn"><i class="icon-collapse"></i> <%=t('link.more')%></span>
  <ul>
    <li>
      <%= link_to new_group_path(@school) do %>
        <i class="icon-plus"></i><%= t('link.new_group') %>
      <% end %>
    </li>
    <li>
      <%= link_to group_path(@school, @group), :confirm => t('general_confirm'), :method => :delete  do %>
      <i class="icon-trash"></i><%= t('link.destroy') %>
      <% end %>
    </li>
  </ul>
</ul>
<% end %>

<% if new_group_management?(@school) %>
  <% content_for :javascript do %>
    <%= javascript_tag "window.USER_SEARCH_URLS = {'group-users-serach': '#{ @group.puavoId }/user_search?words='}" %>
  <% end %>
<% end %>

app/views/groups/user_search.html.erb
<% if @users.length > 0 %>
<% attributes = ["displayName", "uid"] %>
<fieldset class="search_result">
<table class="list widelist">
  <tr class="thead">
    <% attributes.each do |attribute| %>
    <th><%= t("activeldap.attributes.user.#{attribute}") %></th>
    <% end %>
    <th><%= t('activeldap.attributes.school.displayName') %></th>
    <th><%= t('groups.index.actions') %></th>
  </tr>
  <% @users.each do |user| %>
  <tr>
    <td data-title="Name">
      <% if current_user.organisation_owner? || (Array(current_user.puavoAdminOfSchool).map &:to_s).include?(user['puavoSchool']) %>
      <%= link_to user["name"], user_path(user['school_id'], user['id']) %>
      <% else %>
      <%=h user["name"] %>
      <% end %>
    </td>
    <% attributes[1..attributes.length].each do |attribute| %>
    <td data-title="<%=t("activeldap.attributes.user.#{attribute}") %>">
      <%=h user[attribute].first %>
    </td>
    <% end %>
    <td data-title="<%= t('activeldap.attributes.school.displayName') %>">
      <%=h @schools[user["school_id"]] %>
    </td>
    <td id="member_status_<%= @group.puavoId.to_s %>_<%= user["id"].to_s %>">
      <% if @group.member?(user["id"]) %>
        <%= t('.member')%>
      <% else %>
        <%= link_to(t('.add_to_group'),
                    add_user_group_path(:school_id => user["school_id"],
                    :id => @group.puavoId, :user_id => user["id"]),
                    :remote => true,
                    :method => :put,
                    :class => "btn") %>
      <% end %>
    </td>
  </tr>
  <% end %>
</table>
</div>
<% end %>