config/routes.rb
PuavoUsers::Application.routes.draw do

  root :to => "schools#index"

  match '/menu' => 'menu#index', :via => :get

  scope :path => "restproxy" do
    match '(*url)' => 'rest#proxy', :via => [:get, :post, :put], :format => false
  end

  scope :path => "users" do
    resources :ldap_services
    resource :organisation_external_services

    scope :path => ':school_id' do
      match 'roles/:id/select_school' => 'roles#select_school', :as => :select_school_role, :via => :get
      match 'roles/:id/select_role' => 'roles#select_role', :as => :select_role_role, :via => :post
      match 'roles/:id/add_group/:group_id' => 'roles#add_group', :as => :add_group_role, :via => :put
      match 'roles/:id/remove_group/:group_id' => 'roles#remove_group', :as => :remove_group_role, :via => :put
      match 'roles/:id/remove_users' => 'roles#remove_users', :as => :remove_users_role, :via => :put
    end

    scope :path => ':school_id' do
      resource :rename_groups
      resources :roles
    end
    resources :roles

    namespace :schools do
      scope :path => ':school_id' do
        resource :external_services
      end
    end

    scope :path => ':school_id' do
      resources :printer_permissions
    end

    scope :path => ':school_id' do
      match 'lists' => 'lists#index', :as => :lists, :via => :get
      match 'lists/:id' => 'lists#download', :as => :download_list, :via => :post
    end

    match 'schools/:id/admins' => 'schools#admins', :as => :admins_school, :via => :get
    match 'schools/:id/add_school_admin/:user_id' => 'schools#add_school_admin', :as => :add_school_admin_school, :via => :put
    match 'schools/:id/remove_school_admin/:user_id' => 'schools#remove_school_admin', :as => :remove_school_admin_school, :via => :put
    match 'schools/:id/wlan' => 'schools#wlan', :as => :wlan_school, :via => :get
    match 'schools/:id/wlan_update' => 'schools#wlan_update', :as => :wlan_update_school, :via => :put
    match 'schools/:id/external_services' => 'external_services#index', :as => :external_services_school, :via => :get
    resources :schools

    scope :path => ':school_id' do
      match "groups/:id/remove_user/:user_id" => "groups#remove_user", :as => "remove_user_group", :via => :put
      match "groups/:id/add_user/:user_id" => "groups#add_user", :as => "add_user_group", :via => :put
      match "groups/:id/user_search" => "groups#user_search", :as => :user_search, :via => :get
      match 'groups/:id/members' => 'groups#members', :as => :add_role_group, :via => :get
      match 'groups/:id/add_role/:role_id' => 'groups#add_role', :as => :add_role_group, :via => :put
      match 'groups/:id/delete_role/:role_id' => 'groups#delete_role', :as => :delete_role_group, :via => :put
      match 'users/:id/select_school' => 'users#select_school', :as => :select_school_user, :via => :get
      match 'users/:id/select_role' => 'users#select_role', :as => :select_role_user, :via => :post
      match 'users/change_school' => 'users#change_school', :as => :change_school_users, :via => :post
      match 'users/:id/group' => 'users#group', :as => :group_user, :via => :get
      match 'users/:id/add_group' => 'users#add_group', :as => :add_group_user, :via => :put
      match 'import_tool' => 'import_tool#index', :via => :get
      match 'username_redirect/:username' => 'users#username_redirect', :via => :get, :constraints => { :username => /[^\/]+/ }
    end


    scope :path => ':school_id' do
      resources :users
      match 'users/:id/image' => 'users#image', :as => :image_user, :via => :get
    end

    resources :users

    scope :path => ':school_id' do
      resources :groups
    end
    resources :groups

    match '/login' => 'sessions#new', :as => :login, :via => :get
    match '/login' => 'sessions#create', :as => :login, :via => :post
    match '/logout' => 'sessions#destroy', :as => :logout, :via => :delete
    match '/logo' => 'sessions#logo', :as => :logo, :via => :get, :format => :png
    match '/login/helpers' => 'sessions#login_helpers', :as => :login_helpers, :via => :get, :format => :js
    match '/login/theme' => 'sessions#theme', :as => :login_theme, :via => :get, :format => :css

    resources :sessions
    match 'schools/:id/image' => 'schools#image', :as => :image_school, :via => :get
    match '/' => 'schools#index'
    match ':school_id/users/import/refine' => 'users/import#refine', :as => :refine_users_import, :via => :post
    match ':school_id/users/import/validate' => 'users/import#validate', :as => :validate_users_import, :via => [:post]
    match ':school_id/users/import/new' => 'users/import#new', :as => :new_users_import, :via => :get
    match ':school_id/users/import/status/:job_id' => 'users/import#status', :as => :import_status, :via => :get
    match ':school_id/users/import/render_pdf/:job_id' => 'users/import#render_pdf', :as => :render_pdf, :via => :post
    match ':school_id/users/import/' => 'users/import#create', :as => :create_users_import, :via => :post
    match ':school_id/users/import/user_validate' => 'users/import#user_validate', :as => :user_validate_users_import, :via => :post
    match ':school_id/users/import/options' => 'users/import#options', :as => :options_users_import, :via => :get
    match ':school_id/users/import/download' => 'users/import#generate_passwords_pdf', :as => :generate_passwords_pdf, :via => :post

    scope :path => "password" do
      get( '', :to => 'password#edit',
           :as => :password )
      get( 'edit',
           :to => 'password#edit',
           :as => :edit_password )
      get( 'own',
           :to => 'password#own',
           :as => :own_password )
      put( '',
           :to => 'password#update' )
      get( 'forgot',
           :to => 'password#forgot',
           :as => :forgot_password )
      put( 'forgot',
           :to => 'password#forgot_send_token',
           :as => :forgot_send_token_password )
      get( ':jwt/reset',
           :to => 'password#reset',
           :as => :reset_password,
           constraints: { jwt: /.+/ } )
      post( ':jwt/reset',
            :to => 'password#reset_update',
            :as => :reset_update_password,
            constraints: { jwt: /.+/ } )
      get( 'successfully/:message',
           :to => 'password#successfully',
           :as => :successfully_password )
    end

    match( 'email_confirm' => 'email_confirm#confirm',
           :as => :confirm_email,
           :via => :put )
    match( 'email_confirm/successfully' => 'email_confirm#successfully',
           :as => :successfully_email_confirm,
           :via => :get )
    match( 'email_confirm/:jwt' => 'email_confirm#preview',
           :as => :preview_email_confirm,
           :via => :get,
           :constraints => { jwt: /.+/ } )

    match 'themes/:theme' => 'themes#set_theme', :as => :set_theme
    resources :admins

    match 'owners' => 'organisations#owners', :as => :owners_organisation, :via => :get
    match 'remove_owner/:user_id' => 'organisations#remove_owner', :as => :remove_owner_organisations, :via => :put
    match 'add_owner/:user_id' => 'organisations#add_owner', :as => :add_owner_organisations, :via => :put

    match 'wlan' => 'organisations#wlan', :as => :wlan_organisation, :via => :get
    match 'wlan_update' => 'organisations#wlan_update', :as => :wlan_update_organisation, :via => :put

    resource :organisation, :only => [:show, :edit, :update]
    match "search" => "users_search#index", :as => :search_index
    resource :profile, :only => [:edit, :update, :show]
    match 'profile/image' => 'profiles#image', :as => :image_profile, :via => :get
  end

  scope :path => "devices" do
    match '/' => 'schools#index'
    match 'sessions/show' => 'api/v1/sessions#show', :via => :get
    resources :sessions

    match 'hosts/types' => 'hosts#types'

    scope :path => ':school_id' do
      match 'devices/:id/select_school' => 'devices#select_school', :as => 'select_school_device', :via => :get
      match 'devices/:id/change_school' => 'devices#change_school', :as => 'change_school_device', :via => :post
      match 'devices/:id/image' => 'devices#image', :as => 'image_device', :via => :get

      resources :devices

      match( 'devices/:id/revoke_certificate' => 'devices#revoke_certificate',
             :as => 'revoke_certificate_device',
             :via => :delete )

    end
    
    match 'servers/:id/image' => 'servers#image', :as => 'image_server', :via => :get
    match( 'servers/:id/revoke_certificate' => 'servers#revoke_certificate',
           :as => 'revoke_certificate_server',
           :via => :delete )
    resources :servers

    namespace :api do
      namespace :v2 do
        match( 'devices/by_hostname/:hostname' => 'devices#by_hostname',
               :as => 'by_hostname_api_v2_device',
               :via => :get )
        resources :devices
        resources :servers
      end
    end

    resources :printers, :except => [:show, :new]

    match "search" => "devices_search#index"

    match '/auth' => 'sessions#auth', :via => :get
    
  end

    namespace :api do
      namespace :v2 do
        match( 'hosts/sign_certificate' => 'hosts#sign_certificate',
               :as => 'hosts_sign_certificate',
               :via => :post,
               :format => :json )
      end
    end

  ["api/v2/", ""].each do |prefix|
    match("#{ prefix }external_files" => "external_files#index", :via => :get)
    match("#{ prefix }external_files" => "external_files#upload", :via => :post)
    match(
      "#{ prefix }external_files/:name" => "external_files#get_file",
      :name => /.+/,
      :format => false,
      :via => :get,
      :as => "download_external_file"
    )
    match(
      "#{ prefix }external_files/:name" => "external_files#destroy",
      :name => /.+/,
      :format => false,
      :via => :delete,
      :as => "destroy_external_file"
    )
  end

end

app/views/shared/_allow_guest_and_personal_device.html.erb
<tr>
  <td class="label_td view"><%= label object.class.to_s.downcase, "puavoAllowGuest" %></td>
  <td class="value_td"><%= translate_boolean_value(object.puavoAllowGuest) %></td>
</tr>

<% if [School, LdapOrganisation].include?(object.class) || ( object.class == Device && object.puavoDeviceType == "laptop" ) %>
<tr>
  <td class="label_td view"><%= label object.class.to_s.downcase, "puavoPersonalDevice" %></td>
  <td class="value_td"><%= translate_boolean_value(object.puavoPersonalDevice) %></td>
</tr>
<% end %>

app/views/shared/_auto_power_off_settings.html.erb
<tr>
  <td class="label_td view"><%= label object.class.human_name, "puavoDeviceAutoPowerOffMode" %></td>
  <td class="value_td">
    <%=h t('puavoDeviceAutoPowerOffMode_' + (object.puavoDeviceAutoPowerOffMode or 'default'),
         :scope => "activeldap.attributes.#{ object.class.human_name }") %>
  </td>
</tr>
<tr>
  <td class="label_td view"><%= label object.class.human_name, "puavoDeviceOnHour" %></td>
  <td class="value_td">
    <%=h object.puavoDeviceOnHour %>
  </td>
</tr>
<tr>
  <td class="label_td view"><%= label object.class.human_name, "puavoDeviceOffHour" %></td>
  <td class="value_td">
    <%=h object.puavoDeviceOffHour %>
  </td>
</tr>

app/views/shared/_automatic_image_updates.html.erb
<tr>
  <td class="label_td view"><%= label object.class.to_s.downcase, "puavoAutomaticImageUpdates" %></td>
  <td class="value_td"><%= translate_boolean_value(object.puavoAutomaticImageUpdates) %></td>
</tr>

app/views/shared/_external_services.html.erb
<h1><span><%= t("external_services.title") %></span></h1>

<p>
  <%= t("external_services.description") %>
</p>

<%= form_tag(put_path, :method => :put) do %>

  <% @external_services.each do |external_service| %>
    <div class="external-services <%= "disabled" if is_disabled?(external_service) %>">
    <h2>
        <%= external_service.cn %>
    </h2>

    <p>
      <%= external_service.description %>
      <% if external_service.puavoServiceDescriptionURL %>
        <a href="<%= external_service.puavoServiceDescriptionURL %>"
           target="_new"><%= t("external_services.additional_info") %></a>
      <% end %>
    </p>

    <table class="list">
      <tr>
        <th>Domain</th>
        <td><%= external_service.puavoServiceDomain %></td>
      </tr>
      <tr>
        <th><%= t("external_services.email") %></th>
        <td><%= external_service.mail  %></td>
      </tr>
      <tr>
        <th><%= t("external_services.path_prefix") %></th>
        <td><%= external_service.puavoServicePathPrefix %></td>
      </tr>
      <tr>
        <th><%= t("external_services.active") %></th>
        <td>
          <%= check_box_tag(
            "puavoActiveService[]",
            external_service.dn,
            is_checked?(external_service),
            :disabled => is_disabled?(external_service)
          )
          %>
        </td>
      </tr>
    </table>

    <% if is_disabled?(external_service) %>
      <p class="organisation-active-notice">
      <%= t("external_services.disabled_description",
            :organisation => link_to(t("external_services.organisation"), organisation_external_services_path)).html_safe %>
      </p>
    <% end %>
    </div>
  <% end %>

  <div class="submit-container">
  <%= submit_tag t("external_services.save") %>
  </div>
<% end %>

app/views/shared/_form_allow_guest_and_personal_device.html.erb
<tr>
  <td class="label_td"><%= f.label :puavoAllowGuest %></td>
  <td>
    <table class="table-in-table">
      <tr>
	<td class="label_td">
	  <%= f.label t("helpers.default"), :for => "device_puavoAllowGuest_" %>
	</td>
	<td class="label_td">
	  <%= f.label t("helpers.boolean_true"), :for => "device_puavoAllowGuest_true" %>
	</td>
	<td class="label_td">
	  <%= f.label t("helpers.boolean_false"), :for => "device_puavoAllowGuest_false" %>
	</td>
      </tr>
      <tr>
	<td>
	  <%= f.radio_button :puavoAllowGuest, "" %>
	</td>
	<td>
	  <%= f.radio_button :puavoAllowGuest, true %>
	</td>
	<td>
	  <%= f.radio_button :puavoAllowGuest, false %>
	</td>
      </tr>
    </table>
  </td>
</tr>

<% if [School, LdapOrganisation].include?(f.object.class) || ( f.object.class == Device && f.object.puavoDeviceType == "laptop" ) %>
<tr>
  <td class="label_td"><%= f.label :puavoPersonalDevice %></td>
  <td>
    <table class="table-in-table">
      <tr>
	<td class="label_td">
	  <%= f.label t("helpers.default"), :for => "device_puavoPersonalDevice_" %>
	</td>
	<td class="label_td">
	  <%= f.label t("helpers.boolean_true"), :for => "device_puavoPersonalDevice_true" %>
	</td>
	<td class="label_td">
	  <%= f.label t("helpers.boolean_false"), :for => "device_puavoPersonalDevice_false" %>
	</td>
      </tr>
      <tr>
	<td>
	  <%= f.radio_button :puavoPersonalDevice, "" %>
	</td>
	<td>
	  <%= f.radio_button :puavoPersonalDevice, true %>
	</td>
	<td>
	  <%= f.radio_button :puavoPersonalDevice, false %>
	</td>
      </tr>
    </table>
  </td>
</tr>
<% end %>

app/views/shared/_form_auto_power_off_settings.html.erb
<tr>
  <td class="label_td"><%= f.label :puavoDeviceAutoPowerOffMode %></td>
  <td>
    <table id="autopoweroff" class="table-in-table">
      <tr>
	<td class="label_td">
	  <%= f.label :puavoDeviceAutoPowerOffMode_default %>
	</td>
	<td class="label_td">
	  <%= f.label :puavoDeviceAutoPowerOffMode_off %>
	</td>
	<td class="label_td">
	  <%= f.label :puavoDeviceAutoPowerOffMode_custom %>
	</td>
      </tr>
      <tr>
	<td>
	  <%= f.radio_button :puavoDeviceAutoPowerOffMode, "default" %>
	</td>
	<td>
	  <%= f.radio_button :puavoDeviceAutoPowerOffMode, "off" %>
	</td>
	<td>
	  <%= f.radio_button :puavoDeviceAutoPowerOffMode, "custom" %>
	</td>
      </tr>
      <tr>
	<td class="label_td"><%= f.label :puavoDeviceOnHour %></td>
	<td class="label_td"><%= f.label :puavoDeviceOffHour %></td>
      </tr>
      <tr>
	<td>
	  <%= f.select( :puavoDeviceOnHour,
              [[t('.select'), '']] + (1..24).each.map{ |h| [h.to_s, h.to_s] },
              :selected => (f.object.puavoDeviceOnHour or "") ) %>
	</td>
	<td>
	  <%= f.select( :puavoDeviceOffHour,
              [[t('.select'), '']] + ( (1..24).map{ |h| [h.to_s, h.to_s] } ),
              :selected => (f.object.puavoDeviceOffHour or "" ) ) %>
	</td>
      </tr>
    </table>
  </td>
</tr>

app/views/shared/_form_boolean_attribute.html.erb
<tr>
  <td class="label_td"><%= f.label attribute %></td>
  <td>
    <table class="table-in-table">
      <tr>
	<td class="label_td">
	  <%= f.label t("helpers.default"), :for => "#{ f.object.class.to_s.downcase }_#{ attribute }_" %>
	</td>
	<td class="label_td">
	  <%= f.label t("helpers.boolean_true"), :for => "#{ f.object.class.to_s.downcase }_#{ attribute }_true" %>
	</td>
	<td class="label_td">
	  <%= f.label t("helpers.boolean_false"), :for => "#{ f.object.class.to_s.downcase }_#{ attribute }_false" %>
	</td>
      </tr>
      <tr>
	<td>
	  <%= f.radio_button attribute, "" %>
	</td>
	<td>
	  <%= f.radio_button attribute, true %>
	</td>
	<td>
	  <%= f.radio_button attribute, false %>
	</td>
      </tr>
    </table>
  </td>
</tr>

app/views/shared/_form_purchase_information.html.erb
<h2><span><%= t('shared.purchase_information') %></span></h2>

<table>
<tr>
  <td class="label_td"><%= f.label :puavoPurchaseDate %></td>
  <td class="purchase_date"><%= f.date_select :puavoPurchaseDate, :include_blank => true %></td>
</tr>
<tr>
  <td class="label_td"><%= f.label :puavoWarrantyEndDate %></td>
  <td class="purchase_date"><%= f.date_select :puavoWarrantyEndDate, :include_blank => true %></td>
</tr>
<tr>
  <td class="label_td"><%= f.label :puavoPurchaseLocation %></td>
  <td><%= f.text_field :puavoPurchaseLocation %></td>
</tr>
 <tr>
  <td class="label_td"><%= f.label :puavoPurchaseURL %></td>
  <td><%= f.text_field :puavoPurchaseURL %></td>
</tr>
 <tr>
  <td class="label_td"><%= f.label :puavoSupportContract %></td>
  <td><%= f.text_field :puavoSupportContract %></td>
</tr>
</table>

app/views/shared/_form_wlan.html.erb
<h2><%= t('.wireless_access_point_setup') %></h2>
<table>

  <tr>
    <td class="label_td"><%= f.label :puavoWlanChannel %></td>
    <td><%= f.select( :puavoWlanChannel,
	              [ [t('.default'), ""],
	                [t('.channel_random'), "random"] ] +
                      (1..13).map{ |i| [i.to_s,i.to_s] } )%></td>
  </tr>
</table>

<h2><%= t('.wireless_network_setup') %></h2>

<table>
  <% (0..4).each do |index| %>

  <tr><td><h4><%= t('.wireless_network_title', :index => index + 1) %></h4></td></tr>
  <tr>
    <td class="label_td">
      <%= label_tag "wlan_name[#{ index }]", t('.wlan_name') %>
    </td>
    <td>
      <%= text_field_tag "wlan_name[#{ index }]", f.object.wlan_name ? f.object.wlan_name[index] : "" %>
    </td>
  </tr>

  <tr>
    <td class="label_td">
      <%= label_tag "wlan_type[#{ index }]", t('.wlan_type') %>
    </td>
    <td>
      <%= select_tag( "wlan_type[#{ index }]",
                      options_for_select([ [t('.select_value_open'), "open"],
                                           [t('.select_value_psk'), "psk"] ], :selected => f.object.wlan_type ? f.object.wlan_type[index] : "" ) )%>
    </td>
  </tr>

  <tr>
    <td class="label_td">
      <%= label_tag "wlan_password[#{ index }]", t('.wlan_password') %>
    </td>
    <td>
      <%= text_field_tag "wlan_password[#{ index }]", f.object.wlan_password ? f.object.wlan_password[index] : "" %>
    </td>
  </tr>

  <tr>
    <td class="label_td">
      <%= label_tag "wlan_ap[#{ index }]", t('.wlan_ap') %>
    </td>
    <td>
      <%= check_box_tag "wlan_ap[#{ index }]", "enabled", f.object.wlan_ap ? f.object.wlan_ap[index] : false %>
    </td>
  </tr>

  <% end %>
  <tr>
    <td></td>
    <td><%= f.submit t('link.update'), :class => 'btn' %></td>
  </tr>
</table>

app/views/shared/_main_information.html.erb
<table class="basic-info">
  <tr>
    <td>
      <div>
		    <% path = device.class == Server ? image_server_path(device) : image_device_path(@school, device) %>
          	<%= image_tag( device.jpegPhoto.nil? ? "computer.png" : path,
                       :class => "image" ) %>
	    </div>
    </td>
    <td>
      <h1><%=h device.puavoHostname %></h1>
        <% if controller_name == "devices" %>
          <p><%= label device.class.to_s.downcase, "puavoDeviceType" %><br />
	          <%= Puavo::CONFIG["device_types"][device.puavoDeviceType]["label"][I18n.locale.to_s] %>
          </p>
        <% end %>
        <p><%= label device.class.to_s.downcase, "puavoTag" %><br />
	        <%=h device.puavoTag %>
        </p>

        <% unless device.classes.include?('puavoPrinter') ||  device.classes.include?('puavoOtherDevice') %>
        <p><%= label device.class.to_s.downcase, "puavoDeviceStatus" %><br />
	        <%=h device.puavoDeviceStatus %>
        </p>
	<% end %>

      </td>
    </tr>
</table>

app/views/shared/_mountpoint.html.erb
<div class="content-box">
<h3><%= t('.title') %></h3>

<table class="widelist">
  <tr>
    <th><%= t('.filesystem') %></th>
    <th><%= t('.path') %></th>
    <th><%= t('.mountpoint') %></th>
    <th><%= t('.options') %></th>
  </tr>
  <% Array(object.puavoMountpoint).each_index do |index| %>
  <tr>
    <td class="value_td"><%=h object.fs[index] %></td>
    <td class="value_td"><%=h object.path[index] %></td>
    <td class="value_td"><%=h object.mountpoint[index] %></td>
    <td class="value_td"><%=h object.options[index] %></td>
  </tr>
  <% end %>
</table>
</div>

app/views/shared/_purchase_information.html.erb
<div class="content-box">
<h3><%= t('shared.purchase_information') %></h3>
<table class="widelist">
<tr>
  <td class="label_td view"><%= label device.class.to_s.downcase, "puavoPurchaseDate" %></td>
  <td class="value_td"><%=h I18n.l(device.puavoPurchaseDate) rescue nil %></td>
</tr>
<tr>
  <td class="label_td view"><%= label device.class.to_s.downcase, "puavoWarrantyEndDate" %></td>
  <td class="value_td"><%=h I18n.l(device.puavoWarrantyEndDate) rescue nil %></td>
</tr>
<tr>
  <td class="label_td view"><%= label device.class.to_s.downcase, "puavoPurchaseLocation" %></td>
  <td class="value_td"><%=h device.puavoPurchaseLocation %></td>
</tr>
<tr>
  <td class="label_td view"><%= label device.class.to_s.downcase, "puavoPurchaseURL" %></td>
  <td class="value_td"><%=h device.puavoPurchaseURL %></td>
</tr>
<tr>
  <td class="label_td view"><%= label device.class.to_s.downcase, "puavoSupportContract" %></td>
  <td class="value_td"><%=h device.puavoSupportContract %></td>
</tr>
</table>
</div>